### ISSUE TITLE
java.lang.IllegalStateException: Connection has been closed

### ISSUE THREAD

**Issue by alvin0319** [WaterdogPE/WaterdogPE#36]
**Describe the bug**

When player try to disconnect, `java.lang.IllegalStateException: Connection has been closed` occur.

**To Reproduce**
1. Connect server
2. Then quit server

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/32565818/106738499-53dd4800-665b-11eb-90d2-b1d6d09a559f.png)

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Distribution] Windows 10 HOME
 - Java Version:
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.24.0, JRE 15 Windows 10 amd64-64-Bit Compressed References 20210121_173 (JIT enabled, AOT enabled)
OpenJ9   - 345e1b09e
OMR      - 741e94ea8
JCL      - 863b523566 based on jdk-15.0.2+7)
```
 - Version of Waterdog: https://github.com/WaterdogPE/WaterdogPE/commit/0e4836435d2697e45a8c2ebc0950b021b61de23c

**Additional context**

My config.yml settings

```yaml
# Waterdog Main Configuration file
# Configure your desired network settings here.


# A list of all downstream proxies that are available right after starting
# address field is formatted using ip:port
# publicAddress is optional and can be set to the ip players can directly connect through
servers:
  lobby1:
    address: my server address
    #public_address: play.myserver.com:19133
listener:

  # The Motd which will be displayed in the server tab of a player and returned during ping
  motd: §bWaterdog§3PE

  # The server priority list. if not changed by plugins, the proxy will connect the player to the first of those servers
  priorities:
  - lobby1

  # The address to bind the server to
  host: 0.0.0.0:19132

  # The maximum amount of players that can connect to this proxy instance
  max_players: 20

  # Map the ip a player joined through to a specific server
  # for example skywars.xyz.com => SkyWars-1
  # when a player connects using skywars-xyz.com as the serverIp, he will be connected to SkyWars-1 directly
  forced_hosts: {}

# Case-Sensitive permission list for players
permissions:
  TobiasDev:
  - waterdog.player.transfer
  - waterdog.player.list
  alemiz003:
  - waterdog.player.transfer
  - waterdog.player.list

# List of permissions each player should get by default
permissions_default:
- waterdog.command.help
- waterdog.command.info

# Whether the debug output in the console should be enabled or not
enable_debug: false

# If enabled encrypted connection between client and proxy will be created
upstream_encryption: true

# If enabled, only players which are authenticated with XBOX Live can join. If disabled, anyone can connect *with any name*
online_mode: true

# If enabled, the proxy will pass information like XUID or IP to the downstream server using custom fields in the LoginPacket
use_login_extras: true

# Forward original address in client data under 'Waterdog_IP' attribute.
ip_forward: false

# Replaces username spaces with underscores if enabled
replace_username_spaces: false

# Whether server query should be enabled
enable_query: true

# If enabled, when receiving a McpeTransferPacket, the proxy will check if the target server is in the downstream list, and if yes, use the fast transfer mechanism
prefer_fast_transfer: true

# Fast-codec only decodes the packets required by the proxy, everything else will be passed rawly. Disabling this can create a performance hit
use_fast_codec: true

# If enabled, the proxy will inject all the proxy commands in the AvailableCommandsPacket, enabling autocompletion
inject_proxy_commands: true

# Upstream server compression ratio(proxy to client), higher = less bandwidth, more cpu, lower vice versa
upstream_compression_level: 6

# Upstream server compression ratio(proxy to downstream server), higher = less bandwidth, more cpu, lower vice versa
downstream_compression_level: 2

# Enable/Disable the resource pack system
enable_packs: true

# Whether texture packs should be enforced
force_apply_packs: false

# You can set maximum pack size in MB to be cached.
pack_cache_size: 16

# Creating threads may be in some situations expensive. Specify minimum count of idle threads per internal thread executors. Set to -1 to auto-detect by core count.
default_idle_threads: -1
```

**Please make sure the bug you are reporting hasn't been reported here already. Duplicate issues will be quickly closed.**
