### ISSUE TITLE
Error when Transferring

### ISSUE THREAD

**Issue by Altamash347** [WaterdogPE/WaterdogPE#55]
**Describe the bug**
When I transferred from `lobby` to `skyblock` server It gave me this error
```
12:47:45 [INFO ] [/103.245.193.188:57660|Altamash347] <-> Upstream has connected (protocol=422)
12:47:46 [INFO ] [/103.245.193.188:57660|Altamash347] -> Downstream [lobby] has connected
12:48:16 [INFO ] [/103.245.193.188:57660|Altamash347] -> Upstream has disconnected
12:48:16 [INFO ] [Altamash347] -> **Disconnected with: Connection to skyblock failed: java.util.concurrent.TimeoutException**
```

**To Reproduce**
1. Go to 'config.yml'
2. change add 2 servers in the server list
3. save it
4. restart the proxy
5. Join the server
6. Transfer from one server to another
7. see the error `Connection to skyblock failed: java.util.concurrent.TimeoutException`

**Expected behavior**
I expected to transfer to the skyblock server without the long loading screen

**Screenshots**
![image](https://user-images.githubusercontent.com/66252903/109297144-58a8ac80-7853-11eb-9818-b2fce2d2fcfc.png)

**Platform (please complete the following information):**
 - OS: Linux
 - Java Version: Java 11
 - Version of Waterdog: Latest

**Additional context**
the main error is this `Connection to skyblock failed: java.util.concurrent.TimeoutException`
I dont know if I mistaken in something but It is showing to me

**Comment by Alemiz112** [comment]
Hello, the `TimeoutException` is thrown when proxy is unable to open connection with your downstream server. Please ensure that you have used correct downstream address and port.

**Comment by Altamash347** [comment]
> Hello, the `TimeoutException` is thrown when proxy is unable to open connection with your downstream server. Please ensure that you have used correct downstream address and port.


Please check my `config.yml` if there is anything not setup correctly, I added the correct IP and PORT and Both the servers are online

```
# Waterdog Main Configuration file
# Configure your desired network settings here.


# A list of all downstream proxies that are available right after starting
# address field is formatted using ip:port
# publicAddress is optional and can be set to the ip players can directly connect through
servers:
  lobby:
    address: 195.201.111.15:26449
    public_address: thedarklands.mooo.com:26449
  skyblock:
    address: 94.130.219.9:32062
    public_address: de18.falixnodes.net:32062
listener:

  # The Motd which will be displayed in the server tab of a player and returned during ping
  motd: §bWaterdog§3PE

  # The server priority list. if not changed by plugins, the proxy will connect the player to the first of those servers
  priorities:
  - lobby

  # The address to bind the server to
  host: 0.0.0.0:48317

  # The maximum amount of players that can connect to this proxy instance
  max_players: 20

  # Map the ip a player joined through to a specific server
  # for example skywars.xyz.com => SkyWars-1
  # when a player connects using skywars-xyz.com as the serverIp, he will be connected to SkyWars-1 directly
  forced_hosts: {}

# Case-Sensitive permission list for players (empty using {})
permissions:
  TobiasDev:
  - waterdog.player.transfer
  - waterdog.player.list
  alemiz003:
  - waterdog.player.transfer
  - waterdog.player.list

# List of permissions each player should get by default (empty using [])
permissions_default:
- waterdog.command.help
- waterdog.command.info
- waterdog.player.transfer

# Whether the debug output in the console should be enabled or not
enable_debug: false

# If enabled encrypted connection between client and proxy will be created
upstream_encryption: true

# If enabled, only players which are authenticated with XBOX Live can join. If disabled, anyone can connect *with any name*
online_mode: true

# If enabled, the proxy will be able to bind to an Ipv6 Address
enable_ipv6: false

# If enabled, the proxy will pass information like XUID or IP to the downstream server using custom fields in the LoginPacket
use_login_extras: true

# Forward original address in client data under 'Waterdog_IP' attribute.
ip_forward: true

# Replaces username spaces with underscores if enabled
replace_username_spaces: false

# Whether server query should be enabled
enable_query: true

# If enabled, when receiving a McpeTransferPacket, the proxy will check if the target server is in the downstream list, and if yes, use the fast transfer mechanism
prefer_fast_transfer: true

# Fast-codec only decodes the packets required by the proxy, everything else will be passed rawly. Disabling this can create a performance hit
use_fast_codec: true

# If enabled, the proxy will inject all the proxy commands in the AvailableCommandsPacket, enabling autocompletion
inject_proxy_commands: true

# Upstream server compression ratio(proxy to client), higher = less bandwidth, more cpu, lower vice versa
upstream_compression_level: 6

# Upstream server compression ratio(proxy to downstream server), higher = less bandwidth, more cpu, lower vice versa
downstream_compression_level: 2

# Enable/Disable the resource pack system
enable_packs: true

# Whether texture packs should be enforced
force_apply_packs: false

# You can set maximum pack size in MB to be cached.
pack_cache_size: 16

# Creating threads may be in some situations expensive. Specify minimum count of idle threads per internal thread executors. Set to -1 to auto-detect by core count.
default_idle_threads: -1

```
